### ISSUE TITLE
API core crashes with the experimental flag

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1356]
When running the `core.Info` api with the `--exp` flag the api crashes 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xff34c0]

goroutine 513 [running]:
github.com/mesg-foundation/engine/server/grpc/core.(*Server).Info(0xc00435e728, 0x16a4440, 0xc003a7f770, 0xc003b047c0, 0xc00435e728, 0x0, 0x0)
        /Users/antho/prog/MESG/engine/server/grpc/core/core.go:33 +0xf0
github.com/mesg-foundation/engine/protobuf/coreapi._Core_Info_Handler.func1(0x16a4440, 0xc003a7f770, 0x120f280, 0xc003b047c0, 0x13, 0xbf5ad61263626f07, 0x2b2f316ca7, 0x20a10e0)
        /Users/antho/prog/MESG/engine/protobuf/coreapi/api.pb.go:261 +0x86
```

**Comment by NicolasMahe** [comment]
the core api has been removed
