### ISSUE TITLE
Issue synchronising to the testnet

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1633]
While running on the testnet in dev, I've got the following issue. After that, no way to sync any block and also impossible to restart, the engine panics with `panic: StateBlockHeight (305441) > StoreBlockHeight (305440)`

```
ERRO[1011] CONSENSUS FAILURE!!!                          err="open /Users/antho/.mesg/mesg-testnet-01/cosmos/app.db/014193.sst: no such file or directory" module=consensus stack="goroutine 7831 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
  /usr/local/Cellar/go/1.13.4/libexec/src/runtime/debug/stack.go:24 +0xa1
github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000ad1c00, 0x26269c0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:611 +0x63
panic(0x22a9ee0, 0xc0045cf620)
  /usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1e0
github.com/tendermint/tm-db.(*goLevelDBIterator).assertNoError(0xc000b6a230)
  /Users/antho/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/go_level_db.go:325 +0xa0
github.com/tendermint/tm-db.(*goLevelDBIterator).Valid(0xc000b6a230, 0xc000eca600)
  /Users/antho/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/go_level_db.go:260 +0x72
github.com/tendermint/tm-db.newPrefixIterator(0xc000af43a0, 0x11, 0x20, 0xc0036d7060, 0x9, 0x9, 0xc0036d7080, 0x9, 0x9, 0x2817ca0, ...)
  /Users/antho/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/prefix_db.go:270 +0x49
github.com/tendermint/tm-db.(*prefixDB).ReverseIterator(0xc000ad5da0, 0xc0036d7060, 0x9, 0x9, 0xc0036d7080, 0x9, 0x9, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/prefix_db.go:141 +0x534
github.com/tendermint/iavl.(*nodeDB).getPreviousVersion(0xc00050d220, 0x4a925, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/iavl@v0.12.4/nodedb.go:252 +0x21b
github.com/tendermint/iavl.(*nodeDB).SaveOrphans(0xc00050d220, 0x4a925, 0xc0043388d0)
  /Users/antho/go/pkg/mod/github.com/tendermint/iavl@v0.12.4/nodedb.go:172 +0xb9
github.com/tendermint/iavl.(*MutableTree).SaveVersion(0xc000bc0360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/iavl@v0.12.4/mutable_tree.go:412 +0x647
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc000e71400, 0x0, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.6/store/iavl/store.go:105 +0x87
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0x4a925, 0xc000ad55f0, 0x0, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.6/store/rootmulti/store.go:528 +0x178
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000026600, 0x0, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.6/store/rootmulti/store.go:203 +0x81
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0011266c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.6/baseapp/baseapp.go:1002 +0x11b
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc0015f7800, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/abci/client/local_client.go:215 +0xe9
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc0004f82a0, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/proxy/app_conn.go:81 +0x5d
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc00013ea10, 0xa, 0x0, 0xc000e0c450, 0x6, 0xc000e0c470, 0xf, 0x4a925, 0xf, 0xc003794460, ...)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:212 +0x2da
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00013ea10, 0xa, 0x0, 0xc000e0c450, 0x6, 0xc000e0c470, 0xf, 0x4a925, 0xf, 0xc003794460, ...)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:166 +0xce9
github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000ad1c00, 0x4a925)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1426 +0xf63
github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000ad1c00, 0x4a925)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1348 +0x441
github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000ad1c00, 0x0, 0x4a925)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1283 +0xd7
github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000ad1c00, 0x4a925, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1320 +0xafc
github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000ad1c00, 0xc004600780, 0xc000d6ac00, 0x28, 0xc00138b801, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1793 +0x2214
github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000ad1c00, 0xc004600780, 0xc000d6ac00, 0x28, 0x0, 0x0, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1624 +0x88
github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000ad1c00, 0x27ef0a0, 0xc003daa6d0, 0xc000d6ac00, 0x28)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:707 +0x702
github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000ad1c00, 0x0)
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:642 +0x556
created by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart
  /Users/antho/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:334 +0x846
```

**Comment by NicolasMahe** [comment]
I have a few issue when syncing the testnet and stopping the engine before it finish to sync.

I check the code, and it seems that we never properly stop tendermint...
we need to call in `core/main.go`:
```
node.Stop()
```

**Comment by antho1404** [comment]
might be related to https://github.com/mesg-foundation/engine/issues/1457
