### ISSUE TITLE
Crash on the engine with the get started

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1805]
The engine on the current dev branch db2c6572121450b196205dc9da59a85c775cf6d4 is crashing when running the get started

```
panic: runtime error: index out of range [0] with length 0
```

```
time="2020-05-04T11:51:44Z" level=info msg=ABCIQuery data= module=rpc path=custom/process/get/HYm5NTWBVNiQQ8vQV7XPVHRvWwJfZ2LpGLt826j2DPJB result="value:\"{\\\"hash\\\":\\\"HYm5NTWBVNiQQ8vQV7XPVHRvWwJfZ2LpGLt826j2DPJB\\\",\\\"name\\\":\\\"balance-notifier\\\",\\\"nodes\\\":[{\\\"key\\\":\\\"node-0\\\",\\\"Type\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Event_\\\",\\\"value\\\":{\\\"event\\\":{\\\"instanceHash\\\":\\\"8dD91Yx9N7kywn8MtQ9PxReWpdjpeGgSMvZsgWcnG27y\\\",\\\"eventKey\\\":\\\"every_10_seconds\\\"}}}},{\\\"key\\\":\\\"node-1-inputs\\\",\\\"Type\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Map_\\\",\\\"value\\\":{\\\"map\\\":[{\\\"Key\\\":\\\"address\\\",\\\"Value\\\":{\\\"Value\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Map_Output_StringConst\\\",\\\"value\\\":{\\\"string_const\\\":\\\"0x2b1892e181cc749b530e6acc0aecfa4cc9c13ac2\\\"}}}},{\\\"Key\\\":\\\"contractAddress\\\",\\\"Value\\\":{\\\"Value\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Map_Output_StringConst\\\",\\\"value\\\":{\\\"string_const\\\":\\\"0x420167d87d35c3a249b32ef6225872fbd9ab85d2\\\"}}}}]}}},{\\\"key\\\":\\\"node-1\\\",\\\"Type\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Task_\\\",\\\"value\\\":{\\\"task\\\":{\\\"instanceHash\\\":\\\"Dt6UEPBp3okG8VjS1osagg8ry6Miv9MgkXMqSzV5FmLg\\\",\\\"taskKey\\\":\\\"balanceOf\\\"}}}},{\\\"key\\\":\\\"node-3-inputs\\\",\\\"Type\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Map_\\\",\\\"value\\\":{\\\"map\\\":[{\\\"Key\\\":\\\"data\\\",\\\"Value\\\":{\\\"Value\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Map_Output_Map_\\\",\\\"value\\\":{\\\"map\\\":[{\\\"Key\\\":\\\"balance\\\",\\\"Value\\\":{\\\"Value\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Map_Output_Ref\\\",\\\"value\\\":{\\\"ref\\\":{\\\"nodeKey\\\":\\\"node-1\\\",\\\"path\\\":{\\\"Selector\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Reference_Path_Key\\\",\\\"value\\\":{\\\"key\\\":\\\"balance\\\"}}}}}}}}]}}}},{\\\"Key\\\":\\\"url\\\",\\\"Value\\\":{\\\"Value\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Map_Output_StringConst\\\",\\\"value\\\":{\\\"string_const\\\":\\\"https://webhook.site/f5c073ab-97c7-4b5c-827b-fcc4e49f3d9c\\\"}}}}]}}},{\\\"key\\\":\\\"node-3\\\",\\\"Type\\\":{\\\"type\\\":\\\"mesg.types.Process_Node_Task_\\\",\\\"value\\\":{\\\"task\\\":{\\\"instanceHash\\\":\\\"HVso8L6QtToBNomhDvnfobygr6YAtmXRAqdkJsw9s36e\\\",\\\"taskKey\\\":\\\"call\\\"}}}}],\\\"edges\\\":[{\\\"src\\\":\\\"node-0\\\",\\\"dst\\\":\\\"node-1-inputs\\\"},{\\\"src\\\":\\\"node-1-inputs\\\",\\\"dst\\\":\\\"node-1\\\"},{\\\"src\\\":\\\"node-1\\\",\\\"dst\\\":\\\"node-3-inputs\\\"},{\\\"src\\\":\\\"node-3-inputs\\\",\\\"dst\\\":\\\"node-3\\\"}],\\\"address\\\":\\\"mesg145ew60xvstwhcu792tmshmdx97ukqklt3gnkkv\\\"}\" height:12 "
time="2020-05-04T11:51:44Z" level=info msg="Served RPC HTTP response" duration=1 method=GET remoteAddr="192.168.112.1:34858" status=200 url=/process/get/HYm5NTWBVNiQQ8vQV7XPVHRvWwJfZ2LpGLt826j2DPJB
panic: runtime error: index out of range [0] with length 0

goroutine 2230 [running]:
google.golang.org/protobuf/internal/filedesc.(*EnumValues).Get(0xc0000c2200, 0x0, 0xc0000c2200, 0xc0047dde70)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/filedesc/desc_list_gen.go:66 +0x4b
google.golang.org/protobuf/internal/impl.newEnumConverter(0x17b4060, 0x123fc20, 0x17b0ba0, 0xc001745b00, 0xc000f326e0, 0xc00000f600)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/convert.go:379 +0x85
google.golang.org/protobuf/internal/impl.newSingularConverter(0x17b4060, 0x123fc20, 0x17b0ba0, 0xc001745b00, 0xc000f32748, 0x6876ab)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/convert.go:138 +0xefa
google.golang.org/protobuf/internal/impl.newListConverter(0x17b4060, 0xc0031c33c0, 0x17b0ba0, 0xc001745b00, 0x11a2e80, 0x0)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/convert_list.go:17 +0xae
google.golang.org/protobuf/internal/impl.NewConverter(0x17b4060, 0xc0031c33c0, 0x17b0ba0, 0xc001745b00, 0x203000, 0x203000)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/convert.go:56 +0x11d
google.golang.org/protobuf/internal/impl.fieldInfoForList(0x17b0ba0, 0xc001745b00, 0x1261f9b, 0x8, 0x0, 0x0, 0x17b4060, 0x11abb60, 0x1261fa5, 0x64, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect_field.go:172 +0xe1
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc000def400, 0x88, 0xffffffffffffffff, 0x70, 0xffffffffffffffff, 0xc002e31890, 0xc002e318c0, 0xc002e318f0, 0xc002e31920)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect.go:61 +0x663
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc000def400, 0x17b4060, 0x134b980, 0x88, 0xffffffffffffffff, 0x70, 0xffffffffffffffff, 0xc002e31890, 0xc002e318c0, 0xc002e318f0, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect.go:36 +0x63
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc000def400)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message.go:91 +0x182
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(0xc000def400)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message.go:73 +0x3c
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc002f3caa0, 0xc000f32f90)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect_gen.go:150 +0x2f
google.golang.org/protobuf/proto.protoMethods(...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal(0x101, 0x177dd00, 0xc0000a0a80, 0xc002cd743a, 0x4, 0x4, 0x17a94a0, 0xc002f3caa0, 0x12586c0, 0x135f260, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/proto/decode.go:76 +0x7f
google.golang.org/protobuf/proto.UnmarshalOptions.UnmarshalState(...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/proto/decode.go:63
google.golang.org/protobuf/internal/impl.consumeMessage(0xc002cd7439, 0x5, 0x5, 0x176af40, 0xc002f3caa0, 0x2, 0x0, 0x177dd00, 0xc0000a0a80, 0xc000e469c0, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/codec_field.go:281 +0x2de
google.golang.org/protobuf/internal/impl.makeMessageFieldCoder.func3(0xc002cd7439, 0x5, 0x5, 0xc002e315c0, 0x2, 0xc000229c20, 0x1289900, 0x177dd00, 0xc0000a0a80, 0xc000f331f8, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/codec_field.go:218 +0x12c
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer(0xc000def180, 0xc002cd7439, 0x6, 0x5, 0xc002e315c0, 0xc000000000, 0x17b4000, 0x177dd00, 0xc0000a0a80, 0xc002e315c0, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/decode.go:137 +0x5c8
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshal(0xc000def180, 0x17a94a0, 0xc002f3c7e0, 0xc002cd7438, 0x6, 0x6, 0x0, 0x177dd00, 0xc0000a0a80, 0xc000f33378, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/decode.go:60 +0xb2
google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal(0x101, 0x177dd00, 0xc0000a0a80, 0xc002cd7438, 0x6, 0x6, 0x17a94a0, 0xc002f3c7e0, 0xd, 0xc000e1c901, ...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/proto/decode.go:87 +0x297
google.golang.org/protobuf/proto.UnmarshalOptions.UnmarshalState(...)
        /Users/antho/go/pkg/mod/google.golang.org/protobuf@v1.21.0/proto/decode.go:63
github.com/golang/protobuf/proto.UnmarshalMerge(0xc002cd7438, 0x6, 0x6, 0x7f218aba5180, 0xc002e315c0, 0xc000f33601, 0xc00183cf90)
        /Users/antho/go/pkg/mod/github.com/golang/protobuf@v1.4.0/proto/wire.go:67 +0x19b
github.com/golang/protobuf/proto.(*Buffer).Unmarshal(0xc00183cf98, 0x7f218aba5180, 0xc002e315c0, 0x0, 0x0)
        /Users/antho/go/pkg/mod/github.com/golang/protobuf@v1.4.0/proto/buffer.go:119 +0x77
google.golang.org/grpc/encoding/proto.codec.Unmarshal(0xc002cd7438, 0x6, 0x6, 0x13294c0, 0xc002e315c0, 0xc000d5e870, 0xc000d5e7b0)
        /Users/antho/go/pkg/mod/google.golang.org/grpc@v1.29.1/encoding/proto/proto.go:93 +0x12e
google.golang.org/grpc.recv(0xc000e46780, 0x7f218ab8b5c0, 0x21ad578, 0xc00011eb00, 0x0, 0x0, 0x13294c0, 0xc002e315c0, 0x400000, 0x0, ...)
        /Users/antho/go/pkg/mod/google.golang.org/grpc@v1.29.1/rpc_util.go:713 +0x10f
google.golang.org/grpc.(*serverStream).RecvMsg(0xc000440600, 0x13294c0, 0xc002e315c0, 0x0, 0x0)
        /Users/antho/go/pkg/mod/google.golang.org/grpc@v1.29.1/stream.go:1473 +0x156
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).RecvMsg(0xc000e46820, 0x13294c0, 0xc002e315c0, 0xc000f338e0, 0x40ce48)
        /Users/antho/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:164 +0x4b
github.com/mesg-foundation/engine/server/grpc/orchestrator._Execution_Stream_Handler(0x1249240, 0xc00105c3c0, 0x1797ee0, 0xc000e46820, 0x28, 0xc00333fc70)
        /Users/antho/prog/MESG/engine/server/grpc/orchestrator/execution.pb.go:418 +0x60
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0x1249240, 0xc00105c3c0, 0x1797e20, 0xc000e46800, 0xc000e467a0, 0x15693e0, 0x1, 0xc000e46800)
```

**Comment by NicolasMahe** [comment]
Can you try with a prod release?

**Comment by antho1404** [comment]
I was running the command `liteflow-dev dev ~/Desktop/get-started` and at the creation of the process had a crash.
This was happening with the dev version and the local build of the engine and the version `local`.
I just deleted all my docker images and rebuilt/re-pull everything and it seems ok, I cannot reproduce it anymore.

**Comment by antho1404** [comment]
Ok, I was not crazy and found a way to reproduce it with the liteflow cli.

Build the docker image for the engine on the `dev` branch `make docker-dev`

```
liteflow init test
cd test
nano process.yml
```
copy this process
```yaml
name: xxxx/test1
steps:
  - type: trigger
    instance:
      src: https://github.com/liteflow-services/js-function
    taskKey: execute
  - type: filter
    conditions:
      result: 50
  - type: task
    instance:
      src: https://github.com/liteflow-services/js-function
    taskKey: execute
    inputs: 
      code: "module.export = function (inputs) { return inputs }"
      inputs: true
```

Run `liteflow dev --version local`

The liteflow cli will crash because of an issue while creating the process and the engine container will contain the errors I put before

**Comment by NicolasMahe** [comment]
I got an issue when using command `liteflow dev` on the process of the get started. But in my case it seems like it's the logs that doesn't work.
