### ISSUE TITLE
panic on TestLogs

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/engine#514]
To reproduce stop all running Docker services and containers.
I don't see this is happening on CI.

```
--- FAIL: TestLogs (3.80s)
panic: No such image: http-server:latest [recovered]
	panic: No such image: http-server:latest

goroutine 51 [running]:
testing.tRunner.func1(0xc4203e20f0)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:742 +0x29d
panic(0x13ed540, 0xc420458b80)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/mesg-foundation/core/daemon.startForTest()
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/daemon/start_test.go:31 +0x21f
github.com/mesg-foundation/core/daemon.TestLogs(0xc4203e20f0)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/daemon/logs_test.go:10 +0x26
testing.tRunner(0xc4203e20f0, 0x1492060)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:824 +0x2e0
FAIL	github.com/mesg-foundation/core/daemon	3.878s
```

**Comment by ilgooz** [comment]
@krhubert I think we can add some lines to integration tests to build these dependency containers at the beginning. Useful in devs machines.
