### ISSUE TITLE
fix TestIsRunning test

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/engine#522]
failing on [CI](https://circleci.com/gh/mesg-foundation/core/3902?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

```
--- FAIL: TestIsRunning (0.62s)
panic: starting container failed: No such network: core [recovered]
	panic: starting container failed: No such network: core

goroutine 70 [running]:
testing.tRunner.func1(0xc4205ae000)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x7f0480, 0xc4203e3f10)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/mesg-foundation/core/daemon.startForTest()
	/go/src/github.com/mesg-foundation/core/daemon/start_test.go:31 +0x21f
github.com/mesg-foundation/core/daemon.TestIsRunning(0xc4205ae000)
	/go/src/github.com/mesg-foundation/core/daemon/status_test.go:51 +0x26
testing.tRunner(0xc4205ae000, 0x8954e8)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL	github.com/mesg-foundation/core/daemon	3.615s
=== RUN   TestDecodeError
```

**Comment by krhubert** [comment]
todo close - we haven't seen it for a while
